export const RESOURCE_DATA = {
  leadType: ['Corporate', 'COD', 'Cash Basis', 'Walking Customer'],
  leadStatus: [
    'Open',
    'Active',
    'Pending',
    'Opportunity',
    'Converted',
    'Deative',
  ],
  idType: ['BR', 'ROC', 'NIC', 'Passport', 'Driving Licence', 'Other'],
  categories: [
    'DOCUMENT',
    'PARCEL',
    'ELECTRONIC GOODS',
    'CHEQUES',
    'CARDS',
    'INVITATION CARDS',
    'PHONE',
    'MEDICAL PRODUCT',
    'LAPTOPS',
    'CREDIT CARD',
    'PARTY COPIES',
    'TENDER',
    'VEHICLE PARTS',
    'WHEEL CHAIR',
    'BED (HOSPITAL)',
    'TELEVISION (TV)',
    'REFRIGERATOR',
    'WASHING MACHINE',
    'SEWING MACHINE',
    'NUMBER PLATES',
    'CR DELIVERY',
    'BIKE (FOOT CYCLE)',
    'FLOWER BOX',
    'FLOWER BOX 1',
    'FLOWER BOX 2',
    'FLOWER BOX 3',
    'BUDDHIST BOOK',
    '5 SET BOOK',
    'STORY BOOK',
    'ORIGAMI BOOK',
    'CAR DOOR',
    'VAN DOOR',
    'BUFFER',
    'FOOT BALL & GOAL',
    'CRICKET BAT & BALL',
    'BADMINTON SET',
    'BASKET BALL & HOOP',
    'TABLE TENIS SET',
    'KIDS SUNGLASSES',
    'RUGBY BALL',
    'FRISBEE',
    'FOOT BALL',
    'BASKET BALL',
    'SKIPPING ROPE',
    'PASSPORT',
    'MOBILE PHONE',
    'MATTRESS',
    'BICYCLE',
    'FLOWER BOX-CUSTOMER PICKING AT HO',
    'FLOWER BOX-CUSTOMER PICKING AT BRANCH',
    'FLOWER BOX-DOOR DELIVERY (1KG TO 10 KG)',
    'FLOWER BOX-DOOR DELIVERY (11KG TO 15KG)',
    'FLOWER BOX-DOOR DELIVERY (ABOVE 16KG)',
    'MOTOR BIKE',
    'NESTOMALT 400GX18',
    'HAMPER',
    'INVITATION GREETING CARDS',
    'CALENDAR & DIARY',
    'GIFT ITEMS & COMPLIMENTS',
    'FLOWERS',
    'PHOTOCOPY MACHINE',
    'STEEL CUPBOARD',
    'CHAIR SET',
    'MAIL BAGS',
    'MAILBAG - GREEN COLOUR',
    'MAILBAG - BLUE COLOUR',
    'MAILBAG - YELLOW COLOUR',
    'MAILBAG - PURPLE COLOUR',
    'CR BOOK',
    'DROP BOX',
    "32' TELEVISION",
    "65' TELEVISION",
    'RECYCLING BINS',
    'LADDERS',
    'OTHERS',
    'TYRES',
    'DRAWERS',
    'KIDS CAR',
    'VISA DOCUMENT',
  ],
  paymentTypes: ['Cash', 'COD', 'Monthly'],
  rateCardDemarcations: [
    'Island-wide',
    'Colombo 1 - 15',
    'Greater Colombo',
    'Colombo Suburbs',
    'Outstation',
    'Remote',
  ],
};
